name: Homebrew

on:
  push:
  # create:
  #   tags:
  #     - v*

jobs:
  build-test:
    name: Build

    strategy:
      matrix:
        runs-on: [macOS-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_COLOR: 1
      HOMEBREW_NO_EMOJI: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta

      - name: Setup environment
        run: |
          brew update-reset /usr/local/Homebrew
          mkdir -p /usr/local/Homebrew/Library/Taps/emsec
          ln -s $PWD /usr/local/Homebrew/Library/Taps/emsec/homebrew-hal

      - name: Audit
        run: brew audit --strict --online hal --verbose

      - name: Style
        run: brew style  hal --verbose

      - name: Build Bottle
        run: brew test-bot hal --root-url="https://dl.bintray.com/emsec/bottles-hal/" --fail-fast --skip-setup --verbose

      - name: Publish Bottle
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          unset HOMEBREW_DISABLE_LOAD_FORMULA
          brew test-bot hal --ci-upload --root-url="https://dl.bintray.com/emsec/bottles-hal/" --bintray-org="emsec" --verbose
          export VERSION_STRING=$(git describe --tag --dirty="" --broken="" --abbrev=0)
          export VERSION_STRING=$(python -c "exec('print(\"$VERSION_STRING\"[1:])')")
          echo "VERSION_STRING=$VERSION_STRING"
          curl -u$(HOMEBREW_BINTRAY_USER):$(HOMEBREW_BINTRAY_KEY) -H Content-Type:application/json -H Accept:application/json -X POST https://api.bintray.com/content/emsec/bottles-hal/hal/$VERSION_STRING/publish -d "{ \"discard\": \"false\" }"

          git push
        env:
          HOMEBREW_BINTRAY_USER: ${{ secrets.HOMEBREW_BINTRAY_USER }}
          HOMEBREW_BINTRAY_KEY: ${{ secrets.HOMEBREW_BINTRAY_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
